# Generated by Django 3.2.9 on 2021-11-05 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=40)),
                ('will_come', models.DateTimeField()),
                ('qr_code', models.ImageField(upload_to='')),
                ('gender', models.CharField(max_length=10)),
                ('date_birth', models.DateField()),
                ('is_came', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('fio', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='')),
                ('passport_seria', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=40)),
                ('came_in', models.DateTimeField(auto_now_add=True)),
                ('cabinet', models.IntegerField(unique=True)),
                ('date_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('passport_image', models.FileField(upload_to='')),
                ('gender', models.CharField(max_length=10)),
                ('live_place_now', models.CharField(max_length=100)),
                ('university_finished_in', models.DateField()),
                ('university_finished_sertificate', models.FileField(upload_to='')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('howmany_patient', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Arxiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=500)),
                ('rate', models.IntegerField()),
                ('conclusion', models.CharField(max_length=500)),
                ('reciepe', models.CharField(max_length=500)),
                ('by_whom', models.CharField(max_length=500)),
                ('clients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.clients')),
            ],
        ),
    ]
